title: eureka!
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://hyorok4487.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: hyorok4487
  twitter: _HelloWorld_p
  facebook: hyorok4487
  email: hyorok1234@naver.com
  #linkedin: brianmaierjr

analytics:
  provider        : "google-gtag"

  google:
    tracking_id   : "UA-250084565-1"
    measurement_id: "G-Y88N8KV4RM"
    anonymize_ip  : #false


comment:
  provider:         "disqus"
  disqus:
    shortname:      "hyorok4487"